
CREATE TABLE BANKINFO(
    BANK_NO VARCHAR2(40) NOT NULL,          -- 계좌번호
    BANK_NAME VARCHAR2(40) NOT NULL,        -- 은행명
    BANK_USER_NAME VARCHAR2(30) NOT NULL,   -- 예금주 명
    BANK_DATE DATE NOT NULL,                -- 계설 날짜
    CONSTRAINT PK_BANKINFO PRIMARY KEY(BANK_NO)
);

SELECT *
FROM BANKINFO;

INSERT INTO BANKINFO VALUES('1', '1', '1', SYSDATE);

SELECT NVL(MAX(LPROD_ID), 0) + 1
FROM LPROD;

SELECT *
FROM LPROD;

SELECT COUNT(*)
FROM LPROD
WHERE LPROD_GU = 'P100';

DELETE LPROD WHERE LPROD_ID > 9;

DESC LPROD;

COMMIT;






